module.exports = [
    {
        month: 0,
        name: "Légumes de Janvier",
        emoji: ":garlic:",
        elements: [
            "Ail",
            "Carotte",
            "Céleri",
            "Chou Blanc",
            "Chou de Bruxelles",
            "Chou rouge",
            "Crosne",
            "Chou Frisé",
            "Courge",
            "Endive",
            "Epinard",
            "Mâche",
            "Salade Frisée",
            "Navet",
            "Oignon",
            "Panais",
            "Poireau",
            "Pomme de Terre de conservation",
            "Salsifi",
            "Topinambour"
        ]
    },
    {
        month: 1,
        name: "Légumes de Février",
        emoji: ":carrot:",
        elements: [
            "Ail",
            "Betterave",
            "Carotte",
            "Céleri-rave",
            "Chou Blanc",
            "Chou de Bruxelles",
            "Chou rouge",
            "Crosne",
            "Chou Frisé",
            "Endive",
            "Epinard",
            "Mâche",
            "Salade Frisée",
            "Navet",
            "Oignon",
            "Panais",
            "Poireau",
            "Pomme de Terre de conservation",
            "Salsifi",
            "Topinambour",
            "Radis"

        ]
    },
    {
        month: 2,
        name: "Légumes de Mars",
        emoji: ":onion:",
        elements: [
            "Ail",
            "Asperge",
            "Betterave",
            "Blette",
            "Carotte",
            "Céleri-rave",
            "Chou",
            "Chou de Bruxelles",
            "Chou-Fleur",
            "Crosne",
            "Endive",
            "Epinard",
            "Salade Frisée",
            "Navet",
            "Oignon",
            "Panais",
            "Poireau",
            "Pomme de Terre de conservation",
            "Salsifi",
            "Topinambour",
            "Radis"
        ]
    },
    {
        month: 3,
        name: "Légumes d'Avril",
        emoji: ":cucumber:",
        elements: [
            "Ail",
            "Artichaut",
            "Asperge",
            "Betterave",
            "Blette",
            "Carotte",
            "Chou-Fleur",
            "Concombre",
            "Endive",
            "Epinard",
            "Salade Frisée",
            "Salade Laitue",
            "Navet",
            "Oignon",
            "Petit Pois",
            "Poireau",
            "Pomme de Terre Primeur",
            "Radis"
        ]
    },
    {
        month: 4,
        name: "Légumes de Mai",
        emoji: ":cucumber:",
        elements: [
            "Ail",
            "Artichaut",
            "Asperge",
            "Aubergine",
            "Betterave",
            "Blette",
            "Carotte",
            "Chou-Fleur",
            "Concombre",
            "Courgette",
            "Epinard",
            "Salade Laitue",
            "Navet",
            "Oignon",
            "Petit Pois",
            "Pomme de Terre Primeur",
            "Radis",
            "Tomate"
        ]
    },
    {
        month: 5,
        name: "Légumes de Juin",
        emoji: ":eggplant:",
        elements: [
            "Ail",
            "Artichaut",
            "Asperge",
            "Aubergine",
            "Betterave",
            "Blette",
            "Brocoli",
            "Carotte",
            "Chou Romanesco",
            "Concombre",
            "Courgette",
            "Epinard",
            "Fenouil",
            "Salade Laitue",
            "Navet",
            "Oignon",
            "Petit Pois",
            "Poivron",
            "Pomme de Terre Primeur",
            "Radis",
            "Tomate"
        ]
    },
    {
        month: 6,
        name: "Légumes de Juillet",
        emoji: ":hot_pepper:",
        elements: [
            "Ail",
            "Artichaut",
            "Asperge",
            "Aubergine",
            "Betterave",
            "Blette",
            "Brocoli",
            "Carotte",
            "Céleri-branche",
            "Chou Romanesco",
            "Concombre",
            "Courgette",
            "Epinard",
            "Fenouil",
            "Haricot vert",
            "Salade Laitue",
            "Oignon",
            "Petit Pois",
            "Poivron",
            "Pomme de Terre Primeur",
            "Radis",
            "Tomate"
        ]
    },
    {
        month: 7,
        name: "Légumes d'Aout",
        emoji: ":broccoli:",
        elements: [
            "Ail",
            "Artichaut",
            "Aubergine",
            "Betterave",
            "Blette",
            "Brocoli",
            "Carotte",
            "Céleri-branche",
            "Chou Blanc",
            "Chou Romanesco",
            "Chou Rouge",
            "Concombre",
            "Courge",
            "Courgette",
            "Epinard",
            "Fenouil",
            "Haricot vert",
            "Salade Frisée",
            "Salade Laitue",
            "Oignon",
            "Petit Pois",
            "Poivron",
            "Pomme de Terre Primeur",
            "Radis",
            "Tomate"
        ]
    },
    {
        month: 8,
        name: "Légumes de Septembre",
        emoji: ":sweet_potato:",
        elements: [
            "Ail",
            "Artichaut",
            "Aubergine",
            "Betterave",
            "Blette",
            "Brocoli",
            "Carotte",
            "Céleri-branche",
            "Chou",
            "Chou Blanc",
            "Chou de Bruxelles",
            "Chou-Fleur",
            "Chou Frisé",
            "Chou Romanesco",
            "Chou Rouge",
            "Concombre",
            "Courge",
            "Courgette",
            "Epinard",
            "Fenouil",
            "Haricot vert",
            "Salade Frisée",
            "Salade Laitue",
            "Oignon",
            "Panais",
            "Patate Douce",
            "Poireau",
            "Poivron",
            "Pomme de Terre Primeur",
            "Potiron",
            "Radis",
            "Tomate"
        ]
    },
    {
        month: 9,
        name: "Légumes d'Octobre",
        emoji: ":potato:",
        elements: [
            "Ail",
            "Aubergine",
            "Betterave",
            "Blette",
            "Brocoli",
            "Carotte",
            "Céleri-branche",
            "Céleri-Rave",
            "Chou",
            "Chou Blanc",
            "Chou de Bruxelles",
            "Chou-Fleur",
            "Chou Frisé",
            "Chou Romanesco",
            "Chou Rouge",
            "Concombre",
            "Courge",
            "Courgette",
            "Echalotte",
            "Endive",
            "Epinard",
            "Fenouil",
            "Haricot vert",
            "Salade Frisée",
            "Salade Laitue",
            "Navet",
            "Oignon",
            "Panais",
            "Patate Douce",
            "Poireau",
            "Poivron",
            "Pomme de Terre de conservation",
            "Potiron",
            "Radis",
            "Rutabaga",
            "Salsifi",
            "Topinambour",
            "Tomate"
        ]
    },
    {
        month: 10,
        name: "Légumes de Novembre",
        emoji: ":leafy_green:",
        elements: [
            "Ail",
            "Betterave",
            "Brocoli",
            "Cardon",
            "Carotte",
            "Céleri-branche",
            "Céleri-Rave",
            "Chou",
            "Chou Blanc",
            "Chou de Bruxelles",
            "Chou-Fleur",
            "Chou Frisé",
            "Chou Rouge",
            "Citrouille",
            "Courge",
            "Crosne",
            "Echalotte",
            "Endive",
            "Epinard",
            "Fenouil",
            "Salade Frisée",
            "Mâche",
            "Navet",
            "Oignon",
            "Panais",
            "Poireau",
            "Pomme de Terre de conservation",
            "Potiron",
            "Radis",
            "Rutabaga",
            "Salsifi",
            "Topinambour"
        ]
    },
    {
        month: 11,
        name: "Légumes de Décembre",
        emoji: ":christmas_tree:",
        elements: [
            "Ail",
            "Betterave",
            "Carotte",
            "Céleri-branche",
            "Céleri-Rave",
            "Chou",
            "Chou Blanc",
            "Chou de Bruxelles",
            "Chou Frisé",
            "Chou Rouge",
            "Courge",
            "Crosne",
            "Echalotte",
            "Endive",
            "Epinard",
            "Salade Frisée",
            "Mâche",
            "Navet",
            "Oignon",
            "Panais",
            "Poireau",
            "Pomme de Terre de conservation",
            "Potiron",
            "Radis",
            "Rutabaga",
            "Salsifi",
            "Topinambour"
        ]
    },
];